# Python CircleCI 2.0 configuration file
# 
# Check https://circleci.com/docs/2.0/language-python/ for more details
# 
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
    # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements-test.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m pip install --user virtualenv
            ~/.local/bin/virtualenv venv
            . venv/bin/activate
            python3 -m pip install -r requirements-test.txt
  test:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
    # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements-test.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: 
          name: run tests
          command: |
            python3 -m pip install --user virtualenv wheel
            #~/.local/bin/virtualenv venv
            #. venv/bin/activate
            python3 -m pip install --user -r requirements-test.txt
            echo "lets do some testing"
            # move test commands to tox.ini
            #~/.local/bin/tox -e venv
            #~/.local/bin/tox 
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
