version: '3'
services:
  cloudlab:
    hostname: cloudlab
    volumes:
      - ..:/home/secdevops
    build:
      context: ..
      dockerfile: docker/Dockerfile
  ruby-test:
    hostname: cloudlab-ruby
    volumes:
      - ..:/home/secdevops
    build:
      context: ..
      dockerfile: docker/Dockerfile.ruby